name: Deployment

on:
  push:
    branches:
      - "main"

env:
  ENVIRONMENT: "production"

jobs:
  build_and_push_image:
    name: Build docker image and push to repo
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prepare.outputs.version }}
      image: ${{ steps.push-image.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        id: docker-login-push
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Prepare parameters
        if: success()
        id: prepare
        run: |
          ORG_NAME="jayjamieson"
          echo ::set-output name=sekret_image::docker.io/${ORG_NAME}/sekret
          echo ::set-output name=version::$(git rev-parse --short HEAD).${GITHUB_RUN_NUMBER}

      - name: Echo Image name
        run: echo ${{ steps.prepare.outputs.sekret_image }}:${{ steps.prepare.outputs.version }}

      - name: Run docker build
        id: docker-build
        run: |
          echo "build ${{ steps.prepare.outputs.sekret_image }}"  
          docker build --build-arg VERSION=${{ steps.prepare.outputs.version }} -t ${{ steps.prepare.outputs.sekret_image }} . --no-cache --rm

      - name: Push image
        id: push-image
        run: |
          docker tag ${{ steps.prepare.outputs.sekret_image }} ${{ steps.prepare.outputs.sekret_image }}:${{ steps.prepare.outputs.version }}
          docker push ${{ steps.prepare.outputs.sekret_image }}:${{ steps.prepare.outputs.version }}
          echo ::set-output name=image::${{ steps.prepare.outputs.sekret_image }}:${{ steps.prepare.outputs.version }}

  deploy_to_heroku:
    name: Deploy to heroku
    needs: build_and_push_image
    runs-on: ubuntu-latest

    steps:
      - name: Login to Heroku Container
        id: heroku-login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Login to DockerHub
        id: docker-login-pull
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Pull and Push to Heroku
        id: pull-push-heroku
        run: |
          ORG_NAME="jayjamieson"
          REPO_NAME="sekret"
          APP_NAME="jay-sekret"
          echo ::set-output name=version::$(git rev-parse --short HEAD).${GITHUB_RUN_NUMBER}
          docker pull "$ORG_NAME/$REPO_NAME":${{ steps.prepare.outputs.version }}
          docker tag "$ORG_NAME/$REPO_NAME":${{ steps.prepare.outputs.version }} "registry.heroku.com/$APP_NAME/web"
          docker push "registry.heroku.com/$APP_NAME/web"
          heroku container:release web -a $APP_NAME
